const plantOptions = [
  { value: "0", label: "작물 선택하기" },
  { value: "eggPlant", label: "가지" },
  { value: "pepper", label: "고추" },
  { value: "sweetPumpkin", label: "단호박" },
  { value: "strawberry", label: "딸기" },
  { value: "lettuce", label: "상추" },
  { value: "watermelon", label: "수박" },
  { value: "squash", label: "애호박" },
  { value: "zucchiniPumpkin", label: "쥬키니호박" },
  { value: "cucumber", label: "오이" },
  { value: "melon", label: "참외" },
  { value: "tomato", label: "토마토" },
  { value: "grape", label: "포도" },
  { value: "potato", label: "감자" },
  { value: "greenOnion", label: "파" },
  { value: "radish", label: "무" },
  { value: "onion", label: "양파" },
  { value: "carrot", label: "당근" },
  { value: "bean", label: "콩" },
  { value: "sesame", label: "깻잎" },
  { value: "sweetPotato", label: "고구마" },
  { value: "napaCabbage", label: "배추" },
  { value: "pumpkin", label: "호박" },
  { value: "cabbage", label: "양배추" },
];

export default plantOptions;
